# Minimal OptionParser type definitions for BetterTranslate
class OptionParser
  def initialize: () { (OptionParser) -> void } -> void
  def banner=: (String) -> String
  def on: (String, String) { (String) -> void } -> void
        | (String, String, String) { (String) -> void } -> void
  def parse!: (Array[String]?) -> void
        | () -> void
end
